# Generated by Django 4.0.5 on 2022-06-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('content', models.TextField()),
                ('summarization', models.TextField()),
                ('link', models.URLField()),
                ('publisher', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('published_date', models.DateField()),
            ],
        ),
    ]
